conf:
  online:  
    urls: # Ссылки на изображения или API PiGallery2            
      #- "some URLs here"
    "tls": false # Проверка подлинности сертификата
  local: 
    directories: # Пути к папкам с изображениями
      #- "some folders here"
    "usePortrait": false # Использовать ли вертикальные изображения вместе с обычными
    "landscapeCoef": 1.2 # Коэффициент по определению ландшафтных изображений (1 - квадратное изображение считается ландшафтным)
    "setQualityControl": true # Проверять ли качество изображений
    "minMps": 2.0 # Минимальное значение мегапикселей (2 - примерно FullHD)
    "maxMps": 35.0 # Максимальное значение мегапикселей
    "enableFileBlacklist": false # Использовать фильтр имён для файлов
    "enableFolderBlacklist": false # Использовать фильтр имён для папок
    blacklist_files: # Чёрный список имён для файлов и/или папок
      #- "Some bad word here"
      #- "Other bad word here"
    blacklist_folders:
      #- "Some bad folders here"
  global:
    "interval": 60 # Интервал смены обоев в секундах
    "useDirectory": true # Использовать папку вместо
    "useUrls": true # Использовать онлайн изображения
    "wallmode": "Crop" # Режим заполнения обоев (Fit, Center, Crop, Span, Stretch, Tile)
